#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "garmin-to-fittrackee"
name = "Garmin to FitTrackee"
description.en = "Synchronize Garmin to fitTrackee"
description.fr = "Synchroniser Garmin avec fitTrackee"

version = "0.8.4~ynh1"

maintainers = ["Thovi98"]

[upstream]
license = "GPL-3.0"
code = "https://github.com/Dryusdan/garmin-to-fittrackee"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]

    [install.garmin_email]
    ask.en = "What’s your Garmin Connect username?"
    type = "string"

    [install.garmin_password]
    ask.en = "What’s the Garmin Connect password?"
    type = "password"

    [install.fittrackee_id]
    ask.en = "What’s your FitTrackee client ID?"
    type = "string"

    [install.fittrackee_secret]
    ask.en = "What’s the FitTrackee secret?"
    type = "string"

    [install.fittrackee_domain]
    ask.en = "FitTrackee domain (! without ``https://``)"
    type = "string"

[resources]
    [resources.system_user]

    [resources.install_dir]

    [resources.apt]
    packages = "python3, python3-venv, cargo"
